### ISSUE TITLE
How to run an example under asyncio?

### ISSUE THREAD

**Issue by nomhoi** [dry-python/returns#1618]
# Bug report

## What's wrong

From here: https://github.com/dry-python/returns#mixing-sync-and-async-code
I've tried with anyio:
```python
import anyio  # or asyncio, or any other lib
from returns.future import Future

async def first() -> int:
    return 1

def second() -> Future[int]:
    return Future(first()).map(lambda num: num + 1)

# We can then pass our `Future` to any library: asyncio, trio, curio.
# And use any event loop: regular, uvloop, even a custom one, etc
print(anyio.run(second().awaitable))
```
I get the result:
```bash
<IO: 2>
```
All fine.

But, when I use asyncio:
```python
import asyncio  # or asyncio, or any other lib
from returns.future import Future

async def first() -> int:
    return 1

def second() -> Future[int]:
    return Future(first()).map(lambda num: num + 1)

# We can then pass our `Future` to any library: asyncio, trio, curio.
# And use any event loop: regular, uvloop, even a custom one, etc
print(asyncio.run(second().awaitable))
```
I've got this traceback:
```python
Traceback (most recent call last):
  File "ffasyncio.py", line 12, in <module>
    print(asyncio.run(second().awaitable))
  File "/usr/lib/python3.7/asyncio/runners.py", line 37, in run
    raise ValueError("a coroutine was expected, got {!r}".format(main))
ValueError: a coroutine was expected, got <bound method Future.awaitable of <Future: <coroutine object async_map at 0x7f444fe2c8c0>>>
sys:1: RuntimeWarning: coroutine 'async_map' was never awaited
sys:1: RuntimeWarning: coroutine 'first' was never awaited
```
What's wrong?

mypy returns this:
```python
ffasyncio.py:12: error: Argument 1 to "run" has incompatible type "Callable[[], Coroutine[Any, Any, IO[int]]]"; expected "Coroutine[Any, Any, <nothing>]"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

## How is that should be

I'd like to get the same result with asyncio as I get with anyio.

## System information

- `python` version: 3.7
- `returns` version: 0.20.0
- `mypy` version: 1.2.0

**Comment by nomhoi** [comment]
Changed to:
print(asyncio.run(second().awaitable()))
Now works.
