### ISSUE TITLE
Multiprocessing Result example 

### ISSUE THREAD

**Issue by galen104** [dry-python/returns#202]
I'm trying a really simple example of `multiprocessing.Pool`

```
def process_test(data: str) -> Result[str, Exception]:
    time.sleep(1)
    print(data)
    return Success(data)   #  <--- with this will crash
    #return data                 <--- with this is ok


def testme():
    pool = multiprocessing.Pool(processes=os.cpu_count())
    # pool = ThreadPool(processes=os.cpu_count())    # <--- with this works

    l = ['test1', 'test2', 'test3', 'test4', 'test5']
    results = pool.imap_unordered(process_test, l)
    pool.close()
    pool.join()


if __name__ == '__main__':
    freeze_support()
    testme()
```

the code give me these errors:

```
test1
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\Alberto\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\Alberto\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Alberto\Anaconda3\lib\multiprocessing\pool.py", line 470, in _handle_results
    task = get()
  File "C:\Users\Alberto\Anaconda3\lib\multiprocessing\connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "C:\Users\Alberto\Anaconda3\lib\site-packages\returns\primitives\container.py", line 32, in __setattr__
    raise ImmutableStateError()
returns.primitives.exceptions.ImmutableStateError

test2
test3
test4
test5
```

NOTE: if I don't return a Result, the program works.

I'm missing something? It's a bug?

**Comment by sobolevn** [comment]
Yes, I am able to reproduce.

And I guess that this is the reason: https://stackoverflow.com/questions/10077471/errors-using-multiprocessing-pool-map-when-reading-from-an-immutable-object

Working on a fix, thanks a lot for reporting it!

**Comment by sobolevn** [comment]
Done! `__setstate__` and `__getstate__` now works:

```
» python ex.py
test4
test3
test1
test2
test5
[<returns.result._Success object at 0x10734a780>, <returns.result._Success object at 0x10734a820>, <returns.result._Success object at 0x10734a870>, <returns.result._Success object at 0x10734a910>, <returns.result._Success object at 0x10734a9b0>]
```
