### ISSUE TITLE
Make sure that we do not lose traceback with .unwrap()

### ISSUE THREAD

**Issue by sobolevn** [dry-python/returns#30]
When we do something like this:

```python
class FetchUserProfile(object):
    """Single responsibility callable object that fetches user profile."""

    #: You can later use dependency injection to replace `requests`
    #: with any other http library (or even a custom service).
    _http = requests

    @pipeline
    def __call__(self, user_id: int) -> Result['UserProfile', Exception]:
        """Fetches UserProfile dict from foreign API."""
        response = self._make_request(user_id).unwrap()
        return self._parse_json(response)

    @safe
    def _make_request(self, user_id: int) -> requests.Response:
        response = self._http.get('/api/users/{0}'.format(user_id))
        response.raise_for_status()
        return response

    @safe
    def _parse_json(self, response: requests.Response) -> 'UserProfile':
        return response.json()
```

In this example `self._make_request(user_id)` may return `Failure[Exception]` and calling unwrap will create new exception, so we might lose the traceback from the original exception.

We need to be sure that it does not happen at all.

**Comment by sobolevn** [comment]
## Case 1

```python
from returns.result import Result, Failure, Success
from returns.functions import pipeline, safe

import requests

class FetchUserProfile(object):
    """Single responsibility callable object that fetches user profile."""

    #: You can later use dependency injection to replace `requests`
    #: with any other http library (or even a custom service).
    _http = requests

    @pipeline
    def __call__(self, user_id: int) -> Result['UserProfile', Exception]:
        """Fetches UserProfile dict from foreign API."""
        response = self._make_request(user_id).unwrap()
        return self._parse_json(response)

    @safe
    def _make_request(self, user_id: int) -> requests.Response:
        raise TypeError('Bug')

    @safe
    def _parse_json(self, response: requests.Response) -> 'UserProfile':
        return response.json()

fetcher = FetchUserProfile()
result = fetcher(1)
raise result.failure()
```

Traceback:

```python
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    raise result.failure()
  File "/Users/sobolev/Documents/github/returns/returns/functions.py", line 34, in decorator
    return Success(function(*args, **kwargs))
  File "test.py", line 21, in _make_request
    raise TypeError('Bug')
TypeError: Bug
```

## Case 2

```python
from returns.result import Result, Failure, Success
from returns.functions import pipeline, safe

import requests

class FetchUserProfile(object):
    """Single responsibility callable object that fetches user profile."""

    #: You can later use dependency injection to replace `requests`
    #: with any other http library (or even a custom service).
    _http = requests

    @pipeline
    def __call__(self, user_id: int) -> Result['UserProfile', Exception]:
        """Fetches UserProfile dict from foreign API."""
        response = self._make_request(user_id).unwrap()
        return self._parse_json(response)

    @safe
    def _make_request(self, user_id: int) -> requests.Response:
        response = self._http.get('/doesnotexist/users/{0}'.format(user_id))
        response.raise_for_status()
        return response

    @safe
    def _parse_json(self, response: requests.Response) -> 'UserProfile':
        return response.json()

fetcher = FetchUserProfile()
result = fetcher(1)
raise result.failure()

```

Traceback:

```python
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    raise result.failure()
  File "/Users/sobolev/Documents/github/returns/returns/functions.py", line 34, in decorator
    return Success(function(*args, **kwargs))
  File "test.py", line 21, in _make_request
    response = self._http.get('/doesnotexist/users/{0}'.format(user_id))
  File "/Users/sobolev/Documents/github/returns/.venv/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/sobolev/Documents/github/returns/.venv/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/sobolev/Documents/github/returns/.venv/lib/python3.6/site-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/Users/sobolev/Documents/github/returns/.venv/lib/python3.6/site-packages/requests/sessions.py", line 462, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/sobolev/Documents/github/returns/.venv/lib/python3.6/site-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/Users/sobolev/Documents/github/returns/.venv/lib/python3.6/site-packages/requests/models.py", line 387, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '/doesnotexist/users/1': No schema supplied. Perhaps you meant http:///doesnotexist/users/1?
```

**Comment by thedrow** [comment]
Can you please check if #57 fixes this issue?

**Comment by sobolevn** [comment]
Done in #57
